title: Tao Wang's Homepage
page-top-title: Tao Wang
top-section-bg-text: Artificial Intelligence
home-subtitle: Tao Wang&enfp;|&enfp;王涛
copyright-text: '&copy; Tao Wang 2023-2025. All Rights Reserved.'
